// Copyright (c) Microsoft Corporation. All rights reserved. See License.txt in the project root for license information.

// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Code Analysis results, point to "Suppress Message", and click 
// "In Suppression File".
// You do not need to add suppressions to this file manually.

// Suppressions for general exceptions caught and logged
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Formatters.EventTextFormatter.#FormatPayload(Microsoft.Practices.EnterpriseLibrary.SemanticLogging.EventEntry)", Justification = "Exceptions are logged")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.SemanticLogging.ObservableEventListener.#OnEventWritten(System.Diagnostics.Tracing.EventWrittenEventArgs)", Justification = "Exceptions are logged")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Sinks.ConsoleSink.#OnNext(System.String,System.Nullable`1<System.ConsoleColor>)", Justification = "Exceptions are logged")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Sinks.FlatFileSink.#OnSingleEventWritten(System.String)", Justification = "Exceptions are logged")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Sinks.FlatFileSink.#WriteEntries()", Justification = "Exceptions are logged")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Sinks.RollingFlatFileSink.#OnSingleEventWritten(System.String)", Justification = "Exceptions are logged")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Sinks.RollingFlatFileSink.#WriteEntries()", Justification = "Exceptions are logged")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Utility.EventEntryExtensions.#TryFormatAsString(Microsoft.Practices.EnterpriseLibrary.SemanticLogging.EventEntry,Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Formatters.IEventTextFormatter)", Justification = "Exceptions are logged")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Utility.EventEntryExtensions.#TryFormatAsStringAndColor(Microsoft.Practices.EnterpriseLibrary.SemanticLogging.EventEntry,Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Formatters.IEventTextFormatter,Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Formatters.IConsoleColorMapper)", Justification = "Exceptions are logged")]

// Suppressions for casing of Opcode
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "Opcode", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Schema.EventSchema.#OpcodeName", Justification = "Uses casing from EventWrittenEventArgs.Opcode")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "opcode", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Schema.EventSchema.#.ctor(System.Int32,System.Guid,System.String,System.Diagnostics.Tracing.EventLevel,System.Diagnostics.Tracing.EventTask,System.String,System.Diagnostics.Tracing.EventOpcode,System.String,System.Diagnostics.Tracing.EventKeywords,System.String,System.Int32,System.Collections.Generic.IEnumerable`1<System.String>)", Justification = "Uses casing from EventWrittenEventArgs.Opcode")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "Opcode", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Schema.EventSchema.#Opcode", Justification = "Uses casing from EventWrittenEventArgs.Opcode")]

// Suppressions for default parameters
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.SemanticLogging.ConsoleLog.#LogToConsole(System.IObservable`1<Microsoft.Practices.EnterpriseLibrary.SemanticLogging.EventEntry>,Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Formatters.IEventTextFormatter,Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Formatters.IConsoleColorMapper)", Justification = "As designed.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.SemanticLogging.ConsoleLog.#CreateListener(Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Formatters.IEventTextFormatter,Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Formatters.IConsoleColorMapper)", Justification = "As designed.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Formatters.EventTextFormatter.#.ctor(System.String,System.String,System.Diagnostics.Tracing.EventLevel,System.String)", Justification = "As designed.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.SemanticLogging.FlatFileLog.#LogToFlatFile(System.IObservable`1<Microsoft.Practices.EnterpriseLibrary.SemanticLogging.EventEntry>,System.String,Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Formatters.IEventTextFormatter,System.Boolean)", Justification = "As designed.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.SemanticLogging.FlatFileLog.#CreateListener(System.String,Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Formatters.IEventTextFormatter,System.Boolean)", Justification = "As designed.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Formatters.JsonEventTextFormatter.#.ctor(Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Formatters.EventTextFormatting,System.String)", Justification = "As designed.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.SemanticLogging.RollingFlatFileLog.#LogToRollingFlatFile(System.IObservable`1<Microsoft.Practices.EnterpriseLibrary.SemanticLogging.EventEntry>,System.String,System.Int32,System.String,Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Sinks.RollFileExistsBehavior,Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Sinks.RollInterval,Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Formatters.IEventTextFormatter,System.Int32,System.Boolean)", Justification = "As designed.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.SemanticLogging.RollingFlatFileLog.#CreateListener(System.String,System.Int32,System.String,Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Sinks.RollFileExistsBehavior,Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Sinks.RollInterval,Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Formatters.IEventTextFormatter,System.Int32,System.Boolean)", Justification = "As designed.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Formatters.XmlEventTextFormatter.#.ctor(Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Formatters.EventTextFormatting,System.String)", Justification = "As designed.")]
