//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Traces](
        ///    [id] [bigint] IDENTITY(1,1) NOT NULL,
        ///    [InstanceName] [nvarchar](1000) NOT NULL,
        ///    [ProviderId] [char](36) NOT NULL,
        ///    [ProviderName] [nvarchar](500) NOT NULL,
        ///    [EventId] [int] NOT NULL,
        ///    [EventKeywords] [bigint] NOT NULL,
        ///    [Level] [nvarchar](50) NOT NULL,
        ///    [Opcode] [int] NOT NULL,
        ///    [Task] [int] NOT NULL,
        ///    [Timestamp] [datetime2] NOT NULL,
        ///    [Version] [int] NOT NULL,
        ///    [FormattedMessage] [nvarchar](max) NULL,
        ///    [Payload] [nvarchar](max) NULL,
        /// CONSTRAINT [PK_Traces] PR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateGenericTable {
            get {
                return ResourceManager.GetString("CreateGenericTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[WriteTraces]
        ///(
        ///  @InsertTraces TracesType READONLY
        ///)
        ///AS
        ///BEGIN
        ///  INSERT INTO [Traces] (
        ///        [InstanceName],
        ///        [ProviderId],
        ///        [ProviderName],
        ///        [EventId],
        ///        [EventKeywords],
        ///        [Level],
        ///        [Opcode],
        ///        [Task],
        ///        [Timestamp],
        ///        [Version],
        ///        [FormattedMessage],
        ///        [Payload]
        ///    )
        ///  SELECT * FROM @InsertTraces;
        ///END
        ///.
        /// </summary>
        internal static string CreateProcedureWriteTraces {
            get {
                return ResourceManager.GetString("CreateProcedureWriteTraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Traces] (
        ///    [id] [bigint] IDENTITY(1,1) NOT NULL,
        ///    [InstanceName] [nvarchar](1000) NOT NULL,
        ///    [ProviderId] [uniqueidentifier] NOT NULL,
        ///    [ProviderName] [nvarchar](500) NOT NULL,
        ///    [EventId] [int] NOT NULL,
        ///    [EventKeywords] [bigint] NOT NULL,
        ///    [Level] [nvarchar](50) NOT NULL,
        ///    [Opcode] [int] NOT NULL,
        ///    [Task] [int] NOT NULL,
        ///    [Timestamp] [datetimeoffset](7) NOT NULL,
        ///    [Version] [int] NOT NULL,
        ///    [FormattedMessage] [nvarchar](max) NULL,
        ///    [Payload] [nvarchar](max) NULL,
        ///    -- only  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateTracesTable {
            get {
                return ResourceManager.GetString("CreateTracesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TYPE TracesType AS TABLE
        ///(
        ///  [InstanceName] [nvarchar](1000),
        ///    [ProviderId] [uniqueidentifier],
        ///    [ProviderName] [nvarchar](500),
        ///    [EventId] [int],
        ///    [EventKeywords] [bigint],
        ///    [Level] [nvarchar](50),
        ///    [Opcode] [int],
        ///    [Task] [int],
        ///    [Timestamp] [datetimeoffset](7),
        ///    [Version] [int],
        ///    [FormattedMessage] [nvarchar](max),
        ///    [Payload] [nvarchar](max)
        ///);
        ///.
        /// </summary>
        internal static string CreateTracesType {
            get {
                return ResourceManager.GetString("CreateTracesType", resourceCulture);
            }
        }
    }
}
